title: Isabel Dalisay
logo: /assets/img/logo.png
description: A portfolio to find all my projects relating to Computer Science, Data Science, and ArcGIS
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
